version: '3.7'

services:
  # main:
  #   container_name: main
  #   build:
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - ${SERVER_PORT:-3400}:${SERVER_PORT:-3400}
  #     - 9229:9229
  #   command: npm run start:debug
  #   env_file:
  #     - .env
  #   networks:
  #     - webnet
  #   depends_on:
  #     - postgres
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    networks:
      - webnet
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE_NAME:-autopte}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80
    networks:
      - webnet
    restart: unless-stopped
    logging:
      driver: none
networks:
  webnet:
volumes:
  pgdata:
  pgadmin:
