### Vars

@baseUrl = http://localhost:3400

### Root
GET {{baseUrl}}/

### Login
# @name login
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "email": "paul@paul.com",
    "password": "Parol4!"
}

### Register
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "paul@p.com",
    "password": "Parol4!",
    "firstName": "Paul",
    "lastName": "Negoescu"
}

### Set our authToken variable to be available on future requests
@authToken = {{login.response.body.access_token}}
@authToken = {{register.response.body.access_token}}

### List all users
GET {{baseUrl}}/users

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "email": "paul@paul.com",
    "password": "Parol4!",
    "firstName": "Paul",
    "lastName": "Negoescu"
}
